const quotes =[
    "RUN 'Peter Parker' RUN!! ",
    "'slightly autistic nitpic'",
    "'Every now and then, God taps me on the sholder and says, yo I want you to do this right here - Kanye West'",
    "'why do I have to keep assuring people that I know what I'm doing?'",
    "'I dont believe in consistency'",
    "'I'd be damned, the prodigal son returns'",
    "'watch the swag'",
    "'damn I'm good'",
    "'I've never lost a case- ..but also this is my first case'",
    "'IM CLEARLY VAN GOUH IN THE FUCKING FLESH'",
    "'thingos'",
    "'Being a twink is hard'",
    "'forgor'",
    "'Geneava Convention? did we get this tickets year?'",
    "'let's pick up a trade, fuck this school shit'",
    "'Get smoked like a blunt, hippie'",
    "'WAIT NO, NOT MY J'S'",
    "'Get smoked like a blunt hippie'",
    "'lol i havent got a clue'",
    "'well that is my best'",
    "'i think im missing something'",
    "you you missed the third 'the'",
    "'is he stupid why would he do that'",
    "go ahead keep reloading the page",
    "'jarvis drop my needle'",
    "thats a dumb font",
    "you actually like die rise?",

]