const quotes =[
    "RUN 'Peter Parker' RUN!! ",
    "'slightly autistic nitpic'",
    "'Every now and then, God taps me on the sholder and says, yo I want you to do this right here - Kanye West'",
    "'why do I have to keep assuring people that I know what I'm doing?'",
    "'I dont believe in consistency'",
    "'I'd be damned, the prodigal son returns'",
    "'watch the swag'",
    "'damn I'm good'",
    "'I've never lost a case- ..but also this is my first case'",
    "'IM CLEARLY VAN GOUH IN THE FUCKING FLESH'",
    "'thingos'",
    "'Being a twink is hard'",
    "'forgor'",
    "'Geneava Convention? did we get this tickets year?'",
    "'let's pick up a trade, fuck this school shit'",
    "'Get smoked like a blunt, hippie'",
    "'WAIT NO, NOT MY J'S'",
    "'Get smoked like a blunt hippie'",
    "'lol i havent got a clue'",
    "'well that is my best'",
    "'i think im missing something'",
    "you you missed the third 'the'",
    "'is he stupid why would he do that'",
    "go ahead keep reloading the page",
    "'jarvis drop my needle'",
    "thats a dumb font",
    "you actually like die rise?",
    "smormu",
    "House MD is peak",
    "i own a musket for home defense since thats what the founding fathers intended",
    "Dan O'grady im sorry",
    "rest in peace popsmoke",
    "Miku in fortnite?",
    "LiPo batteries without any safety discharge are cheaper though",
    "everything i say might be satire",
    "legally, i dont have to admit anything",
    "ah - the bath",
    "whats up jonathan",
    "I think it might be old man dystixia",
    "cause im a gamer AND a scientist, this is very important to me",
    "to get a REAL shuffed deck of cards, shuffle it at least ~7 times",
    "zoomer femboy liberal gets owned by proud conservative white writer",
    "say 'the finals' 3 times and ill summon like beatle juice",
    "i dont take opinions from mexicans with jjk pfps",
    "MIKE REBUILD THE SET, REBUILD MY KIDS",
    "said the man fixing his CAD",
    "Fabuluos... University education, you cant beat it",
    "being a computer toucher is so hard when ur fucking stupid and know nothing about computers",
    "HE WAS INTO AGE PLAY- HE THOUGHT I WAS 6?!",
    "music brings all togther - Marcos M",
    "JOSE GET THE FUCK OFF THE ROOF",
    "Going to do Straightedge and Compass Construction",
    "i was going to call myself jeb (j-web) but that was taken",
    "maybe i should be called Jwb:tty0",
    "ever since i was young i wanted to transform unstructured data into actionable buiness insights",
    "most will starve",
    "yeah night shift aint to bad...",
    "Im sorry but i dont take opinions from mexicans with jkk pfps",
    "a genuis at enginnering but a little bit of an oddball",
    "being a computer toucher is hard when ur fucking stupid and know nothing about computers",
    "ah to be autistic from 2009-2016 ",
    "simplicity is the ulti-BLAH-BLA-BLAH",
    "the c96 looks so sexy",
    "why cant i have boobs",
    "why do i feel maternal towards technologic baby - my ugly ass son",
    "1 - SO FUCKING TRUE",
    "0 - THATS THE FAKEST STATMENT IVE EVER HEARD",
    "boy the money i made this guy, you wouldnt think he would turn on me",
    "oh thats inflation of my comfort character"

    

]